Repository LNP-BP/client_side_validation, pull requests merged in 2022-03, with the labels that each got.

#48 Taproot support
  .github/workflows/lint.yml
  Cargo.lock
  Cargo.toml
  commit_verify/Cargo.toml
  single_use_seals/Cargo.toml
  strict_encoding/Cargo.toml
  strict_encoding/src/bitcoin.rs
  strict_encoding/src/miniscript.rs
  strict_encoding/src/pointers.rs
  strict_encoding/test_helpers/Cargo.toml
Labels: bug, upstream, ci, *compatibility*, *consensus*

#55 Version bump & updates
  .github/workflows/build.yml
  Cargo.lock
  Cargo.toml
  LICENSE
  README.md
  commit_verify/Cargo.toml
  commit_verify/LICENSE
  commit_verify/src/api.rs
  commit_verify/src/commit_encode.rs
  commit_verify/src/digests.rs
  commit_verify/src/lib.rs
  commit_verify/src/merkle.rs
  commit_verify/src/multi_commit.rs
  commit_verify/src/tagged_hash.rs
  license_header
  single_use_seals/Cargo.toml
  single_use_seals/LICENSE
  single_use_seals/src/lib.rs
  src/api.rs
  src/lib.rs
  strict_encoding/LICENSE
  strict_encoding/derive/LICENSE
  strict_encoding/derive/src/lib.rs
  strict_encoding/derive/tests/basics-failures/no_empty_types/main.rs
  strict_encoding/derive/tests/basics-failures/no_networking_units/mod.rs
  strict_encoding/derive/tests/basics-failures/no_strict_unions/mod.rs
  strict_encoding/derive/tests/basics-failures/no_unit_types/main.rs
  strict_encoding/derive/tests/basics-failures/strict_network_exclusivity/mod.rs
  strict_encoding/derive/tests/basics.rs
  strict_encoding/derive/tests/common/mod.rs
  strict_encoding/derive/tests/enums.rs
  strict_encoding/derive/tests/tlv-failures/no_enums/mod.rs
  strict_encoding/derive/tests/tlv-failures/no_strict/mod.rs
  strict_encoding/derive/tests/tlv-failures/no_unions/mod.rs
  strict_encoding/derive/tests/tlv-failures/tlv_non_u16_type/mod.rs
  strict_encoding/derive/tests/tlv-failures/tlv_undeclared/mod.rs
  strict_encoding/derive/tests/tlv.rs
  strict_encoding/derive_helpers/src/decode.rs
  strict_encoding/derive_helpers/src/encode.rs
  strict_encoding/derive_helpers/src/lib.rs
  strict_encoding/derive_helpers/src/param.rs
  strict_encoding/derive_helpers/tests/derive.rs
  strict_encoding/src/amplify_types.rs
  strict_encoding/src/bitcoin.rs
  strict_encoding/src/bitcoin_hashes.rs
  strict_encoding/src/collections.rs
  strict_encoding/src/crypto.rs
  strict_encoding/src/lib.rs
  strict_encoding/src/macros.rs
  strict_encoding/src/miniscript.rs
  strict_encoding/src/net.rs
  strict_encoding/src/pointers.rs
  strict_encoding/src/primitives.rs
  strict_encoding/src/slice32.rs
  strict_encoding/src/strategies.rs
  strict_encoding/src/test_helpers.rs
  strict_encoding/test_helpers/src/lib.rs
Labels: ci

#56 Refactor commit-embed API
  commit_verify/src/api.rs
  commit_verify/src/commit_verify.rs
  commit_verify/src/digests.rs
  commit_verify/src/embed_commit.rs
  commit_verify/src/lib.rs
Labels: epic, *security*, *consensus*, refactoring

#45 Implement strict en-/decoding with const generics
  strict_encoding/src/net.rs
  strict_encoding/src/pointers.rs
Labels: enhancement, *consensus*, refactoring

#57 Fix issue with miniscript generic recursion in strict encoding
  Cargo.lock
  strict_encoding/Cargo.toml
  strict_encoding/src/miniscript.rs
Labels: bug, *compatibility*, *consensus*

#58 Improve commit_embed API
  commit_verify/src/embed_commit.rs
Labels: enhancement, *security*, *compatibility*, *consensus*

#59 Fix const generic array strict encoding size limits
  Cargo.lock
  Cargo.toml
  commit_verify/Cargo.toml
  strict_encoding/Cargo.toml
  strict_encoding/src/pointers.rs
Labels: bug, *security*

#60 Strict encoding for miniscript descriptor inner types
  .github/workflows/build.yml
  Cargo.lock
  strict_encoding/Cargo.toml
  strict_encoding/src/miniscript.rs
Labels: enhancement

#63 Refactor commitment schemes
  Cargo.lock
  commit_verify/Cargo.toml
  commit_verify/src/commit_encode.rs
  commit_verify/src/commit_verify.rs
  commit_verify/src/embed_commit.rs
  commit_verify/src/lib.rs
  commit_verify/src/merkle.rs
  commit_verify/src/multi_commit.rs
Labels: epic, *consensus*, refactoring

#64 Make EmbedCommitProof::restore_original_container failable
  Cargo.lock
  commit_verify/Cargo.toml
  commit_verify/src/embed_commit.rs
Labels: refactoring
